In [1]:
import numpy as np


In [2]:
ar=np.arange(8)
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
type(ar)



numpy.ndarray

In [5]:
import array as arr

In [6]:
newarray=np.arange(8)
newarray

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
newarray.size

8

In [8]:
len(a)


NameError: name 'a' is not defined

In [9]:
ar.dtype


dtype('int32')

In [10]:
ar.shape


(8,)

In [11]:
print(ar.reshape(4,2))
print(newarray.reshape(2,4))


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [12]:
print(ar+1)


[1 2 3 4 5 6 7 8]


In [13]:
print(ar/2)


[0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [16]:
A=np.array([[2,3],[3,4]])
A

array([[2, 3],
       [3, 4]])

In [22]:
B=np.array([[20],[5]])
B

array([[20],
       [ 5]])

In [21]:
c=np.linalg.solve(A,B)
c

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 2)